### ISSUE TITLE
[功能请求]现在项目已经较为完善，可以开始优化速度了。

### ISSUE THREAD

**Issue by mephisX** [kxxt/aspeak#10]
现在稍微长一点的一句话，获取速度都是十秒钟起。太慢了。
如果是因为免费 API 所导致的问题，请求可以自定义 API

**Comment by kxxt** [comment]
这个问题主要是和网速以及 Azure Cognitive Services 的响应速度有关的，此程序仅仅是提供访问相应服务的一个 CLI, 很难在速度上作出显著的优化。

如有特殊需要可以联系 Azure 方面的技术支持。
