### ISSUE TITLE
Running in python script

### ISSUE THREAD

**Issue by Funktionar** [kxxt/aspeak#11]
How can I run this in my python script, just that without text being typed in, there would be used translated_text instead:
  `def speak_paste():
    try:
        spoken_text = driver1.find_element_by_xpath("/html/body/div/div[2]/div[3]/span").text
        test_str = (spoken_text)
        res = " ".join(lookp_dict.get(ele, ele) for ele in test_str.split())
        pyperclip.copy(res)
        translator = deepl.Translator('') 
        result = translator.translate_text((res), target_lang="ru", formality="less", preserve_formatting="1")  
        translated_text = result.text`
This is basically using subtitle text to translate it with deepl, but I want just to pass this translated text to azure tts to synthesize it.

**Comment by kxxt** [comment]
You can do it in two ways:
1. Using `aspeak` API, but the API might change in future versions (The API is not considered stable now. That's why I didn't document it in README.md).
    ```python
    from aspeak import Synthesizer
    ````
    Create a `Synthesizer` instance. Here is the constructor:
    
    https://github.com/kxxt/aspeak/blob/5d452b8a31d5b3208966c041d091301f057c8f96/src/aspeak/synthesizer.py#L10-L12
   
    For `audio_config` and `audio_format`, please refer to [azure cognitive services documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?pivots=programming-language-python&tabs=terminal). You can also look at [`__main__.py`](https://github.com/kxxt/aspeak/blob/main/src/aspeak/__main__.py) and figure it out by yourself.

    Call `text_to_speech`/`ssml_to_speech` method at your choice:
    https://github.com/kxxt/aspeak/blob/5d452b8a31d5b3208966c041d091301f057c8f96/src/aspeak/synthesizer.py#L67
    https://github.com/kxxt/aspeak/blob/5d452b8a31d5b3208966c041d091301f057c8f96/src/aspeak/synthesizer.py#L70
3. Using [`azure-cognitiveservices-speech`](https://pypi.org/project/azure-cognitiveservices-speech/) directly.
    You can use `aspeak` to  obtain a trial token (Note that the token will expire after a short period of time. A call to `renew()` will renew the token):
    ```python
    from aspeak import Token
    token = Token()
    ```
    Then you can use Microsoft's official [`azure-cognitiveservices-speech`](https://pypi.org/project/azure-cognitiveservices-speech/) with this trial token.
    Here is an example to create an instance of `SpeechConfig` using a trial token:
    ```python
    import azure.cognitiveservices.speech as speechsdk
    cfg = speechsdk.SpeechConfig(auth_token=token.token, region=token.region)
    ```

**Comment by Funktionar** [comment]
I did manage to synthesize it but over time it's stops working, so I assume it's the token being expired. I did try to make a define to renew the token on keyboard press but it didn't work, as it seemed like I needed to return it; could you give me a concrete example on how to refresh the token?

**Comment by kxxt** [comment]
> I did manage to synthesize it but over time it's stops working, so I assume it's the token being expired. I did try to make a define to renew the token on keyboard press but it didn't work, as it seemed like I needed to return it; could you give me a concrete example on how to refresh the token?

If you are using the `Synthesizer` API, it should handle the expiration automatically.

If you just use `aspeak` as a way to obtain a token and then use `azure-cognitiveservices-speech` directly,  you need to recreate the `SpeechConfig` object after you renewed the token.

**Comment by kxxt** [comment]
An easy to use python API is on the way(#12 ), I will provide examples after implementing that feature.

**Comment by Funktionar** [comment]
Using the second method, I just can't call simply `Token.renew()`, doesn't work.

**Comment by kxxt** [comment]
> Using the second method, I just can't call simply `Token.renew()`, doesn't work.

Yes, you need to recreate `SpeechConfig` and even `SpeechSynthesizer` after the renew.

**Comment by Funktionar** [comment]
When will you get the API running?

**Comment by kxxt** [comment]
> When will you get the API running?

Maybe I will release a preview version this weekend.

**Comment by kxxt** [comment]
> When will you get the API running?

A prerelease version v2.0.0.dev1 has been released. I will write the documentations later. There are examples in https://github.com/kxxt/aspeak/tree/feat/api/src/examples

**Comment by kxxt** [comment]
The functional API has been stabilized in v2.0.0.dev2

**Comment by kxxt** [comment]
Maybe I will release a preview version this weekend.
________________________________
