### ISSUE TITLE
Can you add an option for output file name same to text?

### ISSUE THREAD

**Issue by bk111** [kxxt/aspeak#23]
for example, if the text is a simple text, the output name would be same.

aspeak -t "Hello" -ot --mp3
then the output would be "Hello.mp3"

**Comment by kxxt** [comment]
I don't think this is a good idea. Generally speaking, most people won't use `aspeak` in that way. And what if your simple text contains forbidden characters for file path.

You can write a simple bash/powershell script to achieve your goal.
