### ISSUE TITLE
ERROR: Cannot install aspeak because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by qirenzhidao** [kxxt/aspeak#29]
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: Cannot install aspeak==0.1, aspeak==0.1.1, aspeak==0.2.0, aspeak==0.2.1, aspeak==0.3.0, aspeak==0.3.1, aspeak==0.3.2, aspeak==1.0.0, aspeak==1.1.0, aspeak==1.1.1, aspeak==1.1.2, aspeak==1.1.3, aspeak==1.1.4, aspeak==1.2.0, aspeak==1.3.0, aspeak==1.3.1, aspeak==1.4.0, aspeak==1.4.1, aspeak==1.4.2, aspeak==2.0.0, aspeak==2.0.1, aspeak==2.1.0, aspeak==3.0.0, aspeak==3.0.1 and aspeak==3.0.2 because these package versions have conflicting dependencies.

**Comment by kxxt** [comment]
What command do you use to install aspeak? And please show me the full log.

**Comment by qirenzhidao** [comment]
pip install -U aspeak

> What command do you use to install aspeak? And please show me the full log.

**Comment by kxxt** [comment]
> pip install -U aspeak
> 
> > What command do you use to install aspeak? And please show me the full log.

Please show me the full log. I guess there are more outputs from pip. And by the way what's your OS and architecture(x86/x86_64/other)?

**Comment by kxxt** [comment]
v4.0 has been released. Please open another issue if this issue persists with v4.
