### ISSUE TITLE
Error: 'gbk' codec can't decode byte 0xac in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by danangua** [kxxt/aspeak#3]
aspeak -f 296.txt -l zh-cn
Error: 'gbk' codec can't decode byte 0xac in position 2: illegal multibyte sequence
While 296.txt is UTF-8 text file.

UTF8 is more popular than GBK nowadays.

**Comment by kxxt** [comment]
Should be fixed in v1.1.2
