### ISSUE TITLE
Speech synthesis canceled: CancellationReason.Error WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR USP state: 4. Received audio size: 1998720 bytes.

### ISSUE THREAD

**Issue by RouderSky** [kxxt/aspeak#30]
Speech synthesis canceled: CancellationReason.Error
WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR USP state: 4. Received audio size: 1998720 bytes.

**Comment by kxxt** [comment]
Please read README.md carefully.

> ## Important Notice
> 
> Microsoft made some breaking changes to how the trial page works, which breaks `aspeak < 3.0.0.dev1`.
> 
> For old users, to continue to use aspeak, you need to upgrade to v3.0 by executing:
> 
> ```sh
> pip install "aspeak>=3.0"
> ```
> 
> If you get the following error, please shorten your input and do not submit issues about it.
> 
> ```
> Error: Speech synthesis canceled: CancellationReason.Error
> WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR USP state: 4. Received audio size: 13965696 bytes.
> ```
