### ISSUE TITLE
After upgrading to 3.1.0, the error still occurs WebSocket upgrade failed.

### ISSUE THREAD

**Issue by carllx** [kxxt/aspeak#36]
[91mError[0m: Speech synthesis canceled: CancellationReason.Error
WebSocket upgrade failed: Unspecified connection error (200). USP state: 2. Received audio size: 0 bytes.

**Comment by kxxt** [comment]
I guess it's just a internet connectivity issue. Just try again.

`aspeak` still works.

**Comment by bikmanwei** [comment]
Same here. 
aspeak 3.1.0>>
Error: Speech synthesis canceled: CancellationReason.Error
Error decoding audio stream, error code: -50

**Comment by kxxt** [comment]
aspeak v4 has already been released. Feel free to open another issue if this error still occurs with aspeak v4.
