### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by renanrox** [kxxt/aspeak#42]
Hi
i'm using this configuration since oct22:

speech = SpeechToFileService(voice="pt-BR-AntonioNeural", audio_format=AudioFormat(FileFormat.MP3, quality=1))

but today this error make the system stop

  File "C:\Users\XX\AppData\Local\Programs\Python\Python310\lib\site-packages\aspeak\api\api.py", line 162, in __init__
    super().__init__(locale, voice, audio_format, None)
  File "C:\Users\XX\AppData\Local\Programs\Python\Python310\lib\site-packages\aspeak\api\api.py", line 43, in __init__
    self._config()
  File "C:\Users\XX\AppData\Local\Programs\Python\Python310\lib\site-packages\aspeak\api\api.py", line 51, in _config
    assert token is not None
AssertionError

can u help me?

**Comment by zhang00lei** [comment]
I had the same problem today

**Comment by kxxt** [comment]
The work on a rust re-implementation of aspeak has begun at https://github.com/kxxt/aspeak/tree/rs.

Of course, I will still accept PRs that make the python implementation of aspeak work again.

**Comment by renanrox** [comment]
i dont have enough skill to solve this issue, so i just can wait to the new releases, and ppray for another high skilled developer to solve this issue .

thx in advance for the hard work

**Comment by flt6** [comment]
This is because speech-to-text page removed token. I will pull a new request to solve this later. Anyway, you can always use it with `mytts`(now in [alt-impl](https://github.com/kxxt/aspeak/tree/alt-impl) branch)

**Comment by kxxt** [comment]
Fixed in v3.2.0 thanks to @flt6.

**Comment by kxxt** [comment]
I have published an experimental preview release of the rust version of aspeak. Feel free to try it out. Mind that it still has bugs and misses some features.

https://github.com/kxxt/aspeak/releases/tag/rs-0.1.0
https://crates.io/crates/aspeak

Note that python is no longer required when using rust aspeak. 
The total size of the new aspeak executable is under 4.0MB, which is very tiny compared to the old python package plus its dependencies.
Just put the binary file in a folder that is in your PATH variable and then execute aspeak in your terminal.

**Comment by Dabbba** [comment]
> I have published an experimental preview release of the rust version of aspeak. Feel free to try it out. Mind that it still has bugs and misses some features.
> 
> https://github.com/kxxt/aspeak/releases/tag/v4.0.0-alpha1 https://crates.io/crates/aspeak
> 
> Note that python is no longer required when using rust aspeak. The total size of the new aspeak executable is under 4.0MB, which is very tiny compared to the old python package plus its dependencies. Just put the binary file in a folder that is in your PATH variable and then execute aspeak in your terminal.

Thanks for the new version! But... How to install version v4.0.0-alpha1?

**Comment by kxxt** [comment]
> Thanks for the new version! But... How to install version v4.0.0-alpha1?

@Dabbba For now you can download it in github releases: https://github.com/kxxt/aspeak/releases/tag/v4.0.0-alpha.2
Only Windows and Linux builds are available now. Later I will setup CI to support most platforms (MacOS for example).

When the work on python binding is done, 4.0 will be available on PyPI again.
