### ISSUE TITLE
Error:     0: Websocket error    1: TLS error: native-tls error: connection closed via error    2: native-tls error: connection closed via error    3: connection closed via error

### ISSUE THREAD

**Issue by cnmeeia** [kxxt/aspeak#48]
Error: 
   0: Websocket error
   1: TLS error: native-tls error: connection closed via error
   2: native-tls error: connection closed via error
   3: connection closed via error

Location:
   /Users/mick/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/aspeak-4.0.0/src/main.rs:73

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
mick@192 ~ %

**Comment by kxxt** [comment]
This error usually means that you have a poor internet connection to Azure cognitive services.

**Comment by cnmeeia** [comment]
> This error usually means that you have a poor internet connection to Azure cognitive services.

怎么办！请指点

**Comment by kxxt** [comment]
> > This error usually means that you have a poor internet connection to Azure cognitive services.
> 
> 怎么办！请指点

如果你在中国大陆, 你有时可能需要挂梯子(比如透明代理), 不过我这边现在不用梯子也可以访问. 其他的网络问题也有可能导致这个错误. 如果这个错误持续发生, 你可以 reopen 这个 issue.
