### ISSUE TITLE
可以添加声音质量定义吗？

### ISSUE THREAD

**Issue by mephisX** [kxxt/aspeak#5]
现有的默认音频质量听起来属实有点太朦胧了。

**Comment by hejiadong0608** [comment]
是的，现在默认的是16Khz的，听起来确实不对劲。神经语音应该默认用24Khz。

**Comment by kxxt** [comment]
Implemented in v1.2.0. 
在 v1.2.0 中初步实现了。
后续会加入更加 user friendly 的选项（`-q`: `--quality`）
