### ISSUE TITLE
Support using key 

### ISSUE THREAD

**Issue by yhmickey** [kxxt/aspeak#50]

**Comment by kxxt** [comment]
The websocket API of azure TTS is undocumented. So I need an azure cognitive services subscription to try to figure it out. But unfortunately I don't have a subscription key to test. 

If you can send me a subscription key to help the development of a speak, please email me.

**Comment by yhmickey** [comment]
Please check  your outlook email.
Thank you.

**Comment by kxxt** [comment]
@yhmickey  Thank you for providing your key to help the development of aspeak! Authentication by azure subscription key is now supported in v4.1.0.
