### ISSUE TITLE
WebsocketError with ErrorCode 429

### ISSUE THREAD

**Issue by kxxt** [kxxt/aspeak#56]
The free trial API is heavily rate limited by Microsoft. 

If you are constantly hitting this with an error code 429, please consider registering an Azure account and use aspeak with an azure subscription key. (There is a [free tier](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/))

Or you can try to use the edge tts endpoint which comes with fewer features(You need at least aspeak v4.2.0). You can figure out what options are needed by looking at `edge-tts`'s code:

- https://github.com/rany2/edge-tts/blob/58307ded2632fc2bd3a89779a67d5a2e3f6af798/src/edge_tts/communicate.py#L313-L321
- https://github.com/rany2/edge-tts/blob/58307ded2632fc2bd3a89779a67d5a2e3f6af798/src/edge_tts/communicate.py#L352
- https://github.com/rany2/edge-tts/blob/58307ded2632fc2bd3a89779a67d5a2e3f6af798/src/edge_tts/constants.py#L5-L10

**Comment by babykidp** [comment]
Hi, I registered an Azure account and used aspeak with my subscription key. But I constantly hit some similar errors when I used my configuration file:

Error:
   0: Websocket error
   1: HTTP error: 429 Too Many Requests

Location:
   src\main.rs:79

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Could you help me?

**Comment by kxxt** [comment]
> Hi, I registered an Azure account and used aspeak with my subscription key. But I constantly hit some similar errors when I used my configuration file:

Hi, @babykidp.  What's the command you used and the relevant config entries(`region` and `endpoint`)? 

You should use an official API endpoint instead of the default trial endpoint. For example, for `eastus` region, you can run `aspeak -r eastus -k YOUR_KEY text "Hello World"`.

**Comment by babykidp** [comment]
I use the command:
aspeak --profile "C:\Users\user\.aspeak.toml" text "Hello"

My profile looks like this:

[auth]
endpoint = "https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
region = "eastasia"

**Comment by babykidp** [comment]
And I met another error about endpoint:

Error:
   0: TOML parse error at line 19, column 12
   0:    |
   0: 19 | endpoint = "https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
   0:    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   0: unknown variant `https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken`, expected `Endpoint` or `Region`
   0:

Location:
   src\cli\config.rs:64

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by kxxt** [comment]
> [auth] 
> endpoint = "https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken" 
> region = "eastasia"

The endpoint url should be something like "wss://eastus.api.speech.microsoft.com/cognitiveservices/websocket/v1". You don't need to specify endpoint url if you have specified `region`. The endpoint url setting will be used instead of the region setting if you specified both.

**Comment by kxxt** [comment]
> And I met another error about endpoint:
> 
> Error: 0: TOML parse error at line 19, column 12 0: | 0: 19 | endpoint = "https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken" 0: | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 0: unknown variant `https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken`, expected `Endpoint` or `Region` 0:
> 
> Location: src\cli\config.rs:64
> 
> Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it. Run with RUST_BACKTRACE=full to include source snippets.

This should be a bug of aspeak. I will fix it.

**Comment by babykidp** [comment]
> > [auth]
> > endpoint = "https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
> > region = "eastasia"
> 
> The endpoint url should be something like "wss://eastus.api.speech.microsoft.com/cognitiveservices/websocket/v1". You don't need to specify endpoint url if you have specified `region`. The endpoint url setting will be used instead of the region setting if you specified both.

My Azure Keys and Endpoint page shows the endpoint as: https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken. That's different from the default endpoint.

**Comment by kxxt** [comment]
> My Azure Keys and Endpoint page shows the endpoint as: https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issuetoken. That's different from the default endpoint.

The endpoint url in aspeak config is not the issuetoken API url. A list of TTS endpoints can be found at https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech?tabs=streaming#prebuilt-neural-voices . And you need to change `https://` to `wss://` as aspeak is using the websocket API.

There is a bug that caused the endpoint/region settings in profile ineffective. I will fix it soon.

**Comment by babykidp** [comment]
I see, thank you!

**Comment by kxxt** [comment]
@babykidp  The region setting should now be effective with aspeak [v4.3.1](https://github.com/kxxt/aspeak/releases/tag/v4.3.1). Thanks for your error report.

**Comment by babykidp** [comment]
You're welcome. The new version works well now.

**Comment by kxxt** [comment]
> I found some new error. No matter whether I set the region or not, once I set the endpoint as your guide, a new error occurs. The new version works well when I only specify region.
> 
> [auth] endpoint = "wss://eastasia.tts.speech.microsoft.com/cognitiveservices/v1" region = "eastasia"

Ah, it should be `wss://eastasia.tts.speech.microsoft.com/cognitiveservices/websocket/v1`. There is a subtle difference between the REST API endpoint and the websocket API endpoint.

**Comment by babykidp** [comment]
Thank you for your help. I missed "websocket".

**Comment by kxxt** [comment]
The trial endpoint has been removed in v5.0.
