### ISSUE TITLE
Add support for `Send`

### ISSUE THREAD

**Issue by attila-lin** [kxxt/aspeak#58]
Hi, the use of `RefCell` will cause it hard to use in async runtime. 

It would be nice to enhance this part.

**Comment by kxxt** [comment]
I will try to fix this issue. I am still not very familiar to tokio so I would like to hear you advice about it.

**Comment by kxxt** [comment]
It has been fixed in commit https://github.com/kxxt/aspeak/commit/07ce9c607f923f287cb9cd966574a05b244a03e4 and will land in aspeak v5.0.

**Comment by attila-lin** [comment]
Nice to hear that.
