### ISSUE TITLE
Add support get voice list in lib

### ISSUE THREAD

**Issue by attila-lin** [kxxt/aspeak#68]
Hello~

It is not support in lib but in bin.

And we may make the options better in lib.

For example, make the enum value `locale` and `Role` **iter/to_string**able (with `strum` crate)

**Comment by kxxt** [comment]
Landed in [v5.2.0](https://github.com/kxxt/aspeak/releases/tag/v5.2.0).

> For example, make the enum value locale and Role iter/to_stringable (with strum crate)

I will make some improvements later. (Note that the locale is just a string, not an enum).
