### ISSUE TITLE
No examples on v5.2.0

### ISSUE THREAD

**Issue by SnowyThinker** [kxxt/aspeak#70]
No examples on v5.2.0

**Comment by kxxt** [comment]
What examples do you mean? 

Here are the examples:
https://github.com/kxxt/aspeak#examples

**Comment by SnowyThinker** [comment]
I mean rust code examples

**Comment by SnowyThinker** [comment]
> What examples do you mean?
> 
> Here are the examples: https://github.com/kxxt/aspeak#examples

I mean rust code examples on v5.2.0, please write some examples. 
Thanks.

**Comment by kxxt** [comment]
Two examples are added in [v6.0.0-beta.1](https://github.com/kxxt/aspeak/releases/tag/v6.0.0-beta.1): https://github.com/kxxt/aspeak/tree/v6.0.0-beta.1/examples
