### ISSUE TITLE
控制速率的option “-r x” 不起作用.

### ISSUE THREAD

**Issue by dioxide** [kxxt/aspeak#8]
尝试了几个 voice, -r指定不同的值结果都没有变化.   此外, 该选项的默认值好像是1?  而不是0.04

**Comment by kxxt** [comment]
默认值是 0.04，我在 1.3.0 版本测试是没有问题的，你可以提供复现这个问题的完整命令吗？

```sh
$ aspeak -t "你好，世界！" -v zh-CN-XiaoxiaoNeural -o default.wav
$ aspeak -t "你好，世界！" -v zh-CN-XiaoxiaoNeural -r 1 -o 1.wav 
$ ls -la | grep wav   
-rw-r--r--   1 kxxt kxxt   43822  5月  7 23:34 1.wav
-rw-r--r--   1 kxxt kxxt   85294  5月  7 23:34 default.wav
```

**Comment by kxxt** [comment]
注意这里的 rate 不是试用页面上的 speaking speed.
试用页面上的 speaking speed 对应的 rate 恰好是 0.04，这可能是你所说的 `1`

**Comment by kxxt** [comment]
我改天在文档里提一下这个问题

**Comment by dioxide** [comment]
pbpaste | /usr/local/bin/aspeak -l zh-CN -v zh-CN-YunxiNeural -S assistant -r 0.8

目前我是这么测试的.  这个-r不是指语音的速率么?   我没找到这个参数相关的文档描述.

那如果想指定速率应该如何使用呢?  

3q

**Comment by kxxt** [comment]
Rate 是一个相对值，可正可负，会被乘以100%转换为百分比之后填充到 SSML 里面，你可以通过尝试，找出一个合适的 rate 并使用它

**Comment by kxxt** [comment]
Closed as it is documented now.

**Comment by kxxt** [comment]
> 尝试了几个 voice, -r指定不同的值结果都没有变化. 此外, 该选项的默认值好像是1? 而不是0.04

@dioxide  有一个 bug(#9) 导致在不提供 `-t`/`-s` 选项时 style, rate 和 pitch 不起作用，已在 v1.3.1 中修复
