### ISSUE TITLE
STYLE 在 1.30 中好像不起作用

### ISSUE THREAD

**Issue by mephisX** [kxxt/aspeak#9]
输入命令
`aspeak -f input.txt -v zh-CN-XiaoxiaoNeural -S newscast -F Riff24Khz16BitMonoPcm -o output.wav`
成功输出音频，但是风格和官网上听到的 newscast 风格完全不同，感觉是默认风格

**Comment by kxxt** [comment]
在不提供 `-t`/`-s` 选项时会出现这个 bug, 下一个版本修复
